# Generated by Django 4.1.5 on 2023-01-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_coupen_code_signinbonus_limit_voucher_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInBonusUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=150, null=True)),
                ('coupen_code', models.CharField(max_length=150)),
                ('user_uuid', models.CharField(max_length=150)),
                ('voucher_discount', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
